---
title: "Sales Report with Highcharter"
author: "FinanceR"
output: 
  html_document:
      toc: true 
  theme: bootstrap
  logo: FinanceR/logo-mini.jpg
runtime: shiny
---

```{r setup, include=FALSE}
library(highcharter)
library(dplyr)
library(viridisLite)
library(forecast)
library(treemap)
library(flexdashboard)
library(shiny)
library(shinyjs)

# source("../segmentfault-hackathon-2016/FinanceR/init.R")
#1a6ecc
# tag$script(src="//Users/harryzhu/R/segmentfault-hackathon-2016/FinanceR/js/voice.js")
# includeScript("/Users/harryzhu/R/segmentfault-hackathon-2016/FinanceR/js/voice.js")
# includeScript("/Users/harryzhu/R/segmentfault-hackathon-2016/FinanceR/js/annyang.min.js")
# includeScript('init.js')

# setwd("/Users/harryzhu/R/segmentfault-hackathon-2016/FinanceR/")
# includeScript("js/voice.js")
# includeScript("js/annyang.min.js")

# HTML("<script src=\"FinanceR/js/voice.js\"></script>")
HTML("<script src=\"js/voice.min.js\"></script>")
# HTML("<script>runVoice(true);</script>")

chart <- reactive({return(input$chart)})
forecast <- reactive({return(input$forecast)})

col <- reactive({col = input$color
if (length(col) == 0 || !(col %in% colors())) col = 'black'
return(col)})

thm <- hc_theme(
    colors = c(col, "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

mtcars2 <- mtcars[, c("mpg", "cyl", "wt")]

# Reactive that returns the whole dataset if there is no brush
selectedData <- reactive({
  data <- brushedPoints(mtcars2, input$plot1_brush)
  if (nrow(data) == 0)
    data <- mtcars2
  data
})

```

### Sales Forecast


```{r echo=F,warning=F,error=F,message=F}


# include the module


# call the module
# worldPhonesUI("phones")
# callModule(worldPhones, "phones")


# if(FALSE){
  if(TRUE){
  # if get voive plot
  # AirPassengers %>%
  # forecast(level = 90) %>%
  # hchart() %>%
  # hc_add_theme(thm)

  AirPassengers %>%
  hchart() %>%
  hc_add_theme(thm)

}else{
  renderTable({
    # default plot data
  # selectedData()
  AirPassengers
})

}
```

### Sales by State

```{r echo=F,warning=F,error=F,message=F}
data("USArrests", package = "datasets")
data("usgeojson")

USArrests <- USArrests %>%
  mutate(state = rownames(.))

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list.parse2()

highchart() %>%
  hc_add_series_map(usgeojson, USArrests, name = "Sales",
                    value = "Murder", joinBy = c("woename", "state"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
```

### Sales by Category

```{r, fig.keep='none',echo=F,warning=F,error=F,message=F}
data("Groceries", package = "arules")
dfitems <- tbl_df(Groceries@itemInfo)

set.seed(10)

dfitemsg <- dfitems %>%
  mutate(category = gsub(" ", "-", level1),
         subcategory = gsub(" ", "-", level2)) %>%
  group_by(category, subcategory) %>% 
  summarise(sales = n() ^ 3 ) %>% 
  ungroup() %>% 
  sample_n(31)

tm <- treemap(dfitemsg, index = c("category", "subcategory"),
              vSize = "sales", vColor = "sales",
              type = "value", palette = rev(viridis(6)))

highchart() %>% 
  hc_add_series_treemap(tm, allowDrillToNode = TRUE,
                        layoutAlgorithm = "squarified") %>% 
  hc_add_theme(thm)
```

### Best Sellers

```{r echo=F,warning=F,error=F,message=F}
set.seed(2)

nprods <- 10

dfitems %>% 
  sample_n(nprods) %>% 
  .$labels %>% 
  rep(times = sort(sample( 1e4:2e4, size = nprods), decreasing = TRUE)) %>% 
  factor(levels = unique(.)) %>% 
  hchart(showInLegend = FALSE, name = "Sales", pointWidth = 10) %>% 
  hc_add_theme(thm) %>% 
  hc_chart(type = "bar")
  
```